package bank;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Zen jah
 *
 */
public class Balance extends JFrame {

	/**
	 * Constructori class Balance.
	 * 
	 * @param role 				user/admin
	 * @param customer_id		customer id
	 * @param customer_name		customer name
	 */
	public Balance(String role, String customer_id, String customer_name) {
		this.role = role;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		initComponents();

	}


	public Balance() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form. The
	 * content of this method is always regenerated by the Form Editor.
	 */

	@SuppressWarnings("unchecked")
	private void initComponents() {

		jLabel4 = new javax.swing.JLabel();
		lbal = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txtaccno = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Balance");

		lbal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		lbal.setForeground(new java.awt.Color(0, 51, 204));
		lbal.setText("Balance");

		jLabel2.setText("Firstname");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Account No"));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel1.setText("Enter the Acccount No");

		jButton1.setText("Find");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(43, 43, 43)
												.addComponent(jLabel1))
										.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(
												txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 239,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 12, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE).addComponent(jButton1)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addGap(18, 18, 18)
						.addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
						.addComponent(jButton1)));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel7.setText("");

		jButton3.setText("Cancel");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel9.setText("Customer ID");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel5.setText("");

		homeButton = new JButton("Home");
		homeButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				homeButtonActionPerformed(e);

			}
		});
		homeButton.setForeground(Color.BLACK);
		homeButton.setBackground(new Color(51, 153, 102));

		JLabel jLabel2_1 = new JLabel();
		jLabel2_1.setText("Currency");

		lblNewLabel = new JLabel("");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 11));

		currencyLabel = new JLabel("");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
								.addComponent(lbal, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(currencyLabel).addGap(99))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel4).addGap(131))))
				.addGroup(layout.createSequentialGroup().addGap(38)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel2).addGap(31))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel9).addGap(18)))
								.addComponent(jLabel2_1, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE))
						.addGap(37)
						.addGroup(layout
								.createParallelGroup(
										Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel5)
												.addComponent(jLabel7))
										.addGap(150)
										.addComponent(homeButton, GroupLayout.PREFERRED_SIZE, 93,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jButton3,
												GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE))
								.addComponent(lblNewLabel))
						.addGap(173)));
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(
								layout.createSequentialGroup().addContainerGap()
										.addGroup(layout.createParallelGroup(Alignment.TRAILING).addComponent(jPanel1,
												GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel4)
														.addGap(18)
														.addGroup(layout
																.createParallelGroup(Alignment.BASELINE)
																.addComponent(lbal).addComponent(currencyLabel))))
										.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE).addGroup(
												layout.createParallelGroup(Alignment.TRAILING, false)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(Alignment.BASELINE)
																		.addComponent(jLabel9).addComponent(jLabel7))
																.addGap(25)
																.addGroup(layout.createParallelGroup(Alignment.BASELINE)
																		.addComponent(jLabel2).addComponent(jLabel5))
																.addGap(18)
																.addGroup(
																		layout.createParallelGroup(Alignment.BASELINE)
																				.addComponent(jLabel2_1)
																				.addComponent(lblNewLabel))
																.addGap(118))
														.addGroup(layout.createSequentialGroup().addGroup(layout
																.createParallelGroup(Alignment.BASELINE)
																.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 64,
																		GroupLayout.PREFERRED_SIZE)
																.addComponent(homeButton, GroupLayout.PREFERRED_SIZE,
																		59, GroupLayout.PREFERRED_SIZE))
																.addGap(146)))));
		getContentPane().setLayout(layout);

		pack();
	}

	/**
	 * 'Home' button functionality which returns to the main page.
	 * 
	 * @param evt ActionEvent when clicking on Home button
	 */
	private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {

		MainMenu c = new MainMenu(this.role, this.customer_id, this.customer_name);
		c.permissions(this.role);
		this.hide();
		c.setVisible(true);

	}

	/**
	 * Find button functionality
	 * 
	 * @param evt ActionEvent when clicking on find button
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		checkBalance();

	}

	/**
	 * 'Cancel' button functionality which returns to the main page.
	 * 
	 * @param evt ActionEvent when clicking on Cancel button
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
		dispose();

	}

	/**
	 * Set Account permissions
	 * 
	 * @param role use or admin, could be determinated after login
	 */
	public void permissions(String role) {
		this.role = role;

		if (role.contentEquals("admin")) {

			homeButton.setVisible(false);
		} else {
			homeButton.setVisible(true);

		}

	}

	/**
	 * Set an account by account ID
	 * 
	 * @param id 		account Id
	 */

	public void setAccountNumber(String id) {
		txtaccno.setText(id);
	}

	/**
	 * Check Balance in account
	 */

	public String checkBalance() {
		String accno = txtaccno.getText();
		String result = "fail";

		try {
			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();
			insert = con1.prepareStatement("select c.cust_id,c.firstname,c.lastname,a.balance,a.acc_type "
					+ "from customer c, account a" + " where c.cust_id = a.cust_id and a.acc_id = ? and c.cust_id=?");
			insert.setString(1, accno);
			insert.setString(2, this.customer_id);
			rs1 = insert.executeQuery();

			if (rs1.next() == false) {
				JOptionPane.showMessageDialog(null, "Account No no found");
				jLabel5.setText("");
				lbal.setText("");
			} else {
				String id = rs1.getString(1);
				String firstname = rs1.getString(2);
				String laststname = rs1.getString(3);
				String balance = rs1.getString(4);
				String curerncyTxt = rs1.getString(5);
				jLabel7.setText(this.customer_id);
				jLabel5.setText(this.customer_name);
				lblNewLabel.setText(curerncyTxt);
				currencyLabel.setText(curerncyTxt);

				lbal.setText(balance.trim());
				result = balance;
			}

		} catch (SQLException ex) {
			Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
		}
		return result;
	}

	/**
	 * Variables declaration
	 */
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lbal;
	private javax.swing.JTextField txtaccno;
	private JButton homeButton;
	private String role = "user";
	private String customer_id;
	private String customer_name;
	private JLabel lblNewLabel;
	private JLabel currencyLabel;
	private Connection con1;
	private PreparedStatement insert;
	private PreparedStatement insert2;
	private ResultSet rs1;
}
