
package bank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zen jah
 */
public class CustomerReport extends JFrame {

	/**
	 * Creates new form 'CustomerReport'.
	 * 
	 */
	public CustomerReport() {
		initComponents();

		table_update();
	}

	Connection con1;
	PreparedStatement insert;

	/**
	 * This method is called from within the constructor to initialize the form. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		jButton3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();

		jButton3.setText("Cancel");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "CustomerID", "Firstname", "Lastname", "Street", "City", "Phone", "Mail" }) {
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
					java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);
		if (jTable1.getColumnModel().getColumnCount() > 0) {
			jTable1.getColumnModel().getColumn(0).setResizable(false);
			jTable1.getColumnModel().getColumn(1).setResizable(false);
		}

		jButton1.setText("Cancel");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(33)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 641, GroupLayout.PREFERRED_SIZE))
				.addContainerGap(64, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(32)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)
						.addGap(33).addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(44, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
		dispose();
	}

	/**
	 * 'Cancel' button functionality which returns to the main page.
	 * 
	 * @param evt ActionEvent when clicking on Cancel button
	 */

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		setVisible(false);
		dispose();
	}

	/**
	 * 
	 * Display 'table report' which have customer_id, first_name, last_name, street,
	 * city, phone and mail.
	 * 
	 */

	private void table_update() {
		int CC;
		try {
			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();

			insert = con1.prepareStatement("select id,firstname,lastname,street,city,phone,mail from customer");
			ResultSet Rs = insert.executeQuery();
			ResultSetMetaData RSMD = Rs.getMetaData();
			CC = RSMD.getColumnCount();
			DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
			DFT.setRowCount(0);

			while (Rs.next()) {
				Vector v2 = new Vector();

				for (int ii = 1; ii <= CC; ii++) {
					v2.add(Rs.getString("id"));
					v2.add(Rs.getString("firstname"));
					v2.add(Rs.getString("lastname"));
					v2.add(Rs.getString("street"));
					v2.add(Rs.getString("city"));
					v2.add(Rs.getString("phone"));
					v2.add(Rs.getString("mail"));

				}

				DFT.addRow(v2);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Set Account permissions
	 * 
	 * @param role use or admin, could be determinated after login
	 */
	public void permissions(String role) {
		this.role = role;

	}

	/**
	 * Variables declaration
	 */
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private String role = "user";
	private String customer_id;
	private String customer_name;
}
