
package bank;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Zen jah Class Login that gives access to users after verifying
 *         username and password.
 */
public class Login extends JFrame {


	
	/**
	 * Creates new form 'login'
	 * 
	 */
	public Login() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtuser = new javax.swing.JTextField();
		txtpass = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton2.addActionListener(new ActionListener() {
			/**
			 * 'Cancel' button functionality which returns to the main page.
			 * 
			 * @param evt ActionEvent when clicking on Cancel button
			 */

			public void actionPerformed(ActionEvent e) {
				System.exit(0);
			}
		});
		setSize(1200, 800);
		setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Login");
		setBackground(new java.awt.Color(0, 102, 255));
		setForeground(new java.awt.Color(0, 102, 255));

//		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("asd"));
		// here!!!
		jPanel1.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
		jLabel1.setText("Username");

		jLabel2.setText("Password");

		jButton1.setText("Login");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Cancel");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(75)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel1)
						.addComponent(jLabel2))
					.addGap(52)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(txtuser, GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
						.addComponent(txtpass))
					.addContainerGap(88, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap(284, Short.MAX_VALUE)
					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(34)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel1)
						.addComponent(txtuser, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLabel2)
						.addComponent(txtpass, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
					.addGap(34)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jButton2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
						.addComponent(jButton1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);
		 
		setContentPane(new JLabel(new ImageIcon("C:\\Users\\KNIGHT\\Desktop\\pic\\u.jpg")));

		btnSignUp = new JButton("Sign up");
		btnSignUp.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				btnSignUpActionPerformed(e);
			}
		});
		btnSignUp.setForeground(Color.BLACK);
		btnSignUp.setBackground(new Color(51, 153, 102));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(20)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addContainerGap(2500, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addComponent(btnSignUp)
							.addGap(16))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGap(22)
					.addComponent(btnSignUp)
					.addGap(18)
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(1322, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
//		   setLayout(new BorderLayout());
//		   setLayeredPane((new ImageIcon(this.getClass().getResource("/z.jpg")).getImage())); 
	}

	/**
	 * set required parameters for login (used for unit tests)
	 * 
	 * @param data1 Username
	 * @param data2 Password
	 * 
	 */
	public void setTxtuser(String data1, String data2) {

		txtuser.setText(data1);
		txtpass.setText(data2);

	}

	/**
	 * Verify if username and password do not match.
	 * 
	 * @param test test flag for unit test
	 * @return status of login
	 */

	public String tryLogin(Boolean test) {
		String result = "";

		try {
			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();
			insert = con1.prepareStatement("SELECT * FROM logins\n"
					+ "Join customer on customer.cust_id = logins.whois\n" + "WHERE username=? and password=?\n"
					+ "and  NOT EXISTS (SELECT *  FROM black_list WHERE logins.whois = black_list.whois)");
			insert.setString(1, txtuser.getText());
			insert.setString(2, txtpass.getText());
			rs1 = insert.executeQuery();

			if (rs1.next()) {
				// done
				result = "done";
				this.customer_id = rs1.getString(4);
				this.customer_name = rs1.getString(8) + " " + rs1.getString(9);
				this.role = rs1.getString(5);
				if (!test) {
					MainMenu c = new MainMenu(this.role, this.customer_id, this.customer_name);
					c.permissions(this.role);
					c.setSize(1200, 800);
					this.hide();
					c.setVisible(true);
				}

			} else {
				result = "fail";
				// fail
				txtuser.setText("");
				txtpass.setText("");
				txtuser.requestFocus();
				if (!test) {
					JOptionPane.showMessageDialog(null, "username and password do not matched");
				}
			}
		} catch (Exception e) {

			System.out.println("Failed " + e);

		}

		return result;
	}

	/**
	 * 'Login' button functionality.
	 * 
	 * @param evt ActionEvent when clicking on add button
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		tryLogin(false);
	}

	/**
	 * 'X' button functionality which returns to close.
	 * 
	 * @param evt MouseEvent when clicking on Cancel button
	 */
	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {

		System.exit(0);
	}

	/**
	 * 'Sign up' button and create new customer.
	 * 
	 * @param evt ActionEvent when clicking on add button
	 * 
	 */
	private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {
		Customer cus = new Customer();

		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);
		this.hide();

	}

	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	/**
	 * Variables declaration
	 */
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField txtpass;
	private javax.swing.JTextField txtuser;
	private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
	private String role;
	private String customer_id;
	private String customer_name;

	private JButton btnSignUp;
	Connection con1;
	PreparedStatement insert;
	ResultSet rs1;
}
