
package bank;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Zen jah
 */
public class MainMenu extends JFrame {

	/**
	 * Constructor class MainMenu.
	 * 
	 * @param role
	 * @param customer_id
	 * @param customer_name
	 */
	public MainMenu(String role, String customer_id, String customer_name) {
		this.role = role;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		initComponents();
		lblNewLabel.setText("Welcome " + this.customer_name + ", Customer ID:  " + this.customer_id);
	}

	public MainMenu() {

		initComponents();
	}

	/**
	 *
	 * Add permissions for admin
	 */
	public void permissions(String role) {

		if (role.contentEquals("admin")) {
			jMenu4.setVisible(true);
		} else {
			jMenu4.setVisible(false);

		}

	}

	/**
	 * This method is called from within the constructor to initialize the form. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	private void initComponents() {

		jMenuItem1 = new javax.swing.JMenuItem();
		jDesktopPane1 = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem7 = new javax.swing.JMenuItem();

		jMenuItem1.setText("jMenuItem1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(1200, 800));

		JButton btnNewButton = new JButton("Logout");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				logoutActionPerformed(e);

			}
		});
		btnNewButton.setBackground(new Color(0, 153, 204));
		btnNewButton.setForeground(new Color(0, 102, 255));

		lblNewLabel = new JLabel("");
		lblNewLabel.setFont(new Font("Traditional Arabic", Font.BOLD | Font.ITALIC, 15));

		javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
		jDesktopPane1Layout.setHorizontalGroup(jDesktopPane1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jDesktopPane1Layout.createSequentialGroup().addGap(23)
						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 560, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 514, Short.MAX_VALUE).addComponent(btnNewButton)
						.addGap(22)));
		jDesktopPane1Layout.setVerticalGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jDesktopPane1Layout.createSequentialGroup()
						.addGroup(jDesktopPane1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jDesktopPane1Layout.createSequentialGroup().addGap(18)
										.addComponent(btnNewButton))
								.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(641, Short.MAX_VALUE)));
		jDesktopPane1.setLayout(jDesktopPane1Layout);
		jDesktopPane1.setPreferredSize(new java.awt.Dimension(200, 800));

		jMenu1.setText("New");

		jMenuItem3.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
		jMenuItem3.setText("Account");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu1.add(jMenuItem5);

		jMenuItem5.setText("Deposit");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});

		jMenu3.setText("Transfer");
		jMenu3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			}
		});

		jMenuItem6.setText("New");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu5 = new javax.swing.JMenu();
		jMenuItem8 = new javax.swing.JMenuItem();

		jMenu5.setText("Balance");

		jMenuItem8.setText("Balance Check");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem8);

		jMenuBar1.add(jMenu5);
		jMenu3.add(jMenuItem6);

		jMenuBar1.add(jMenu3);

		mntmNewMenuItem = new JMenuItem("History");
		jMenu3.add(mntmNewMenuItem);

		jMenu4.setText("Report");

		jMenuItem7.setText("Customer Report");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem7);

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		offers = new JMenu("Offers");
		jMenuBar1.add(offers);

		profile = new JMenu("Profile");
		jMenuBar1.add(profile);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jDesktopPane1,
				Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap().addComponent(jDesktopPane1, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}

	/**
	 * 'Log out' button functionality 
	 * @param evt ActionEvent when clicking on add button.

	 * */
	private void logoutActionPerformed(java.awt.event.ActionEvent evt) {
		Login c = new Login();
		this.hide();
		c.setVisible(true);
	}

	/**
	 * 'Account' option functionality.
	 * 
	 * @param evt ActionEvent when clicking on add button.
	 */
	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {

		Account cus = new Account(this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");

		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);

	}

	/**
	 * 'Deposit' option functionality.
	 * 
	 * @param evt ActionEvent when clicking on add button.
	 */
	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {

		Deposit cus = new Deposit(this.role, this.customer_id, this.customer_name);

		if (this.role.equals("admin")) {
			cus.permissions("admin");
			this.getDefaultCloseOperation();

		} else {
			cus.permissions("user");
			this.hide();
		}
		// location + size + visible pt MainMenu
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);

	}

	/**
	 * 'Transfer' option functionality.
	 * 
	 * @param evt ActionEvent when clicking on add button.
	 */
	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {

		Transfer cus = new Transfer(this.role, this.customer_id, this.customer_name);

		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);

	}

	/**
	 * 'CustomerReport' option functionality.
	 * 
	 * @param evt ActionEvent when clicking on add button.
	 */
	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
		CustomerReport cus = new CustomerReport();
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(740, 480);
		cus.setVisible(true);

	}

	/**
	 * 'Balance' option functionality.
	 * 
	 * @param evt ActionEvent when clicking on add button.
	 */
	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {

		Balance cus = new Balance(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(800, 520);
		cus.setVisible(true);

	}

	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainMenu().setVisible(true);
			}
		});
	}

	/**
	 * Variables declaration
	 */
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
	private PopupMenu internalFrame;
	private String role = "user";
	private String customer_id;
	private String customer_name;
	private JMenuItem mntmNewMenuItem;
	private JMenu offers;
	private JMenu profile;
	private JLabel lblNewLabel;
}
