/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.awt.Dimension;
import java.awt.PopupMenu;
import java.awt.Toolkit;

import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JToggleButton;
import javax.swing.JMenu;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author kobinath
 */
public class MainMenu extends JFrame {

	public MainMenu(String role, String customer_id, String customer_name) {
		this.role = role;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		initComponents();
//		lblNewLabel.setText("Welcome " + this.customer_name + ", Customer ID:  " + this.customer_id);
	}

	public MainMenu() {
		// TODO Auto-generated constructor stub
		initComponents();
	}

	public void permissions(String role) {

		if (role.contentEquals("admin")) {
//			add what ever you want to admin permissions 
			jMenu4.setVisible(true);
		} else {
			jMenu4.setVisible(false);

		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem7 = new javax.swing.JMenuItem();
//		this.setPreferredSize(new java.awt.Dimension(1200, 800));

		jMenuItem1.setText("jMenuItem1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(1200, 800));
		setContentPane(new JLabel(new ImageIcon("C:\\Users\\KNIGHT\\Desktop\\pic\\u.jpg")));

		jMenu1.setText("New");

		jMenuItem3.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
		jMenuItem3.setText("Account");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu1.add(jMenuItem5);

		jMenuItem5.setText("Deposit");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});

		jMenu3.setText("Transfer");
		jMenu3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenu3ActionPerformed(evt);
			}
		});

		jMenuItem6.setText("New");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu5 = new javax.swing.JMenu();
		jMenuItem8 = new javax.swing.JMenuItem();

		jMenu5.setText("Balance");

		jMenuItem8.setText("Balance Check");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem8);

		jMenuBar1.add(jMenu5);
		jMenu3.add(jMenuItem6);

		jMenuBar1.add(jMenu3);

		mntmNewMenuItem = new JMenuItem("History");
		mntmNewMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				mntmNewMenuItemActionPerformed(e);
			}
		});
		jMenu3.add(mntmNewMenuItem);

		jMenu4.setText("Report");

		jMenuItem7.setText("Customer Report");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem7);

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		offers = new JMenu("Offers");
		offers.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

			}
		});
		jMenuBar1.add(offers);
		
		mntmNewMenuItem_2 = new JMenuItem("Get offers");
		mntmNewMenuItem_2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				offersActionPerformed(e);
			}
		});
		offers.add(mntmNewMenuItem_2);
		
		mnNewMenu = new JMenu("Virtual Card");
		jMenuBar1.add(mnNewMenu);
		
		mntmNewMenuItem_3 = new JMenuItem("Show Virtual Card details");
		mntmNewMenuItem_3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				VcardActionPerformed(e);

			}
		});
		mnNewMenu.add(mntmNewMenuItem_3);

		profile = new JMenu("Profile");
		jMenuBar1.add(profile);
		
		mntmNewMenuItem_1 = new JMenuItem("Edit Profile");
		mntmNewMenuItem_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				profileActionPerformed(e);
			}
		});
		profile.add(mntmNewMenuItem_1);
		
		mnNewMenu_1 = new JMenu("Logout");
		jMenuBar1.add(mnNewMenu_1);
		
		mntmNewMenuItem_4 = new JMenuItem("Go To Login");
		mntmNewMenuItem_4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				logoutActionPerformed(e);
			}
		});
		mnNewMenu_1.add(mntmNewMenuItem_4);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGap(0, 1200, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGap(0, 756, Short.MAX_VALUE)
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	
	
	
	private void logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		// TODO add your handling code here:
		Login c = new Login();
		this.hide();
		c.setVisible(true);

	}// GEN-LAST:event_jMenuItem3ActionPerformed
	
	
	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		// TODO add your handling code here:
		Account cus = new Account(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");

		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem3ActionPerformed
	
	
	
	private void VcardActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
		// TODO add your handling code here:
		VirtualCard cus = new VirtualCard(this.role, this.customer_id, this.customer_name);

		cus.permissions("admin");
		this.getDefaultCloseOperation();

		
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(1330, 527);
		cus.setVisible(true);

	}
	
	
	private void offersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
		// TODO add your handling code here:
		Offers3 cus = new Offers3(this.role, this.customer_id, this.customer_name);

		if (this.role.equals("admin")) {
			cus.permissions("admin");
			this.getDefaultCloseOperation();

		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(680, 420);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem5ActionPerformed
	
	
	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
		// TODO add your handling code here:
		Deposit cus = new Deposit(this.role, this.customer_id, this.customer_name);

		if (this.role.equals("admin")) {
			cus.permissions("admin");
			this.getDefaultCloseOperation();

		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem5ActionPerformed

	private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenu3ActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_jMenu3ActionPerformed

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem6ActionPerformed
		// TODO add your handling code here:
		Transfer cus = new Transfer(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(640, 520);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem6ActionPerformed
	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
		// TODO add your handling code here:
		CustomerReport cus = new CustomerReport(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(740, 480);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem7ActionPerformed
	

	private void profileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
		// TODO add your handling code here:

		// TODO add your handling code here:
		Profile cus = new Profile(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(740, 480);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem7ActionPerformed
	
	
	
	private void mntmNewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
		// TODO add your handling code here:
		Transaction cus = new Transaction(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(740, 480);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem7ActionPerformed

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem8ActionPerformed
		// TODO add your handling code here:
		Balance cus = new Balance(this.role, this.customer_id, this.customer_name);
		if (this.role.equals("admin")) {
			this.getDefaultCloseOperation();
			cus.permissions("admin");
		} else {
			cus.permissions("user");
			this.hide();
		}
		cus.setLocation(this.dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		cus.setSize(740, 520);
		cus.setVisible(true);

	}// GEN-LAST:event_jMenuItem8ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainMenu().setVisible(true);
			}
		});
	}
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
	private PopupMenu internalFrame;
	private String role = "user";
	private String customer_id;
	private String customer_name;
	private JMenuItem mntmNewMenuItem;
	private JMenu offers;
	private JMenu profile;
	private JMenuItem mntmNewMenuItem_1;
	private JMenuItem mntmNewMenuItem_2;
	private JMenu mnNewMenu;
	private JMenuItem mntmNewMenuItem_3;
	private JMenu mnNewMenu_1;
	private JMenuItem mntmNewMenuItem_4;
}
