/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Image;

/**
 *
 * @author kobinath
 */
public class Offers3 extends JFrame {

	/**
	 * Creates new form Offers
	 */

	
	public Offers3(String role, String customer_id, String customer_name) {
		this.role = role;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		initComponents();
		getData();

	}

	public Offers3() {
		initComponents();
		getData();

	}

	Connection con1;
	PreparedStatement insert;
	PreparedStatement insert2;
	ResultSet rs1;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 153, 51));
		jButton3 = new javax.swing.JButton();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Offer #1"));

		jLabel1.setFont(new Font("Trattatello", Font.BOLD, 14));
		
		lblNewLabel = new JLabel("");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(89)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(jLabel1)
					.addGap(18)
					.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);

		jButton3.setText("Cancel");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		homeButton = new JButton("Home");
		homeButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				homeButtonActionPerformed(e);

			}
		});
		homeButton.setForeground(Color.BLACK);
		homeButton.setBackground(new Color(51, 153, 102));
		
		panel = new JPanel();
		
		panel_1 = new JPanel();
		panel_1.setLayout(null);
		panel_1.setBorder(javax.swing.BorderFactory.createTitledBorder("Offer #3"));
		panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Offer #2"));
		
		label_2 = new JLabel("");
//		Image img1 = new ImageIcon("");
		label_2.setIcon(new ImageIcon("C:\\Users\\KNIGHT\\Desktop\\pic\\logo1.jpeg"));
		
		label_3 = new JLabel("");
//		Image img2 = new ImageIcon(this.getClass().getResource("/logo2.jpeg")).getImage();
		label_3.setIcon(new ImageIcon("C:\\Users\\KNIGHT\\Desktop\\pic\\logo2.jpeg"));
		
		label_4 = new JLabel("");
//		Image img3 = new ImageIcon(this.getClass().getResource("/logo3.jpeg")).getImage();
		label_4.setIcon(new ImageIcon("C:\\Users\\KNIGHT\\Desktop\\pic\\logo3.jpeg"));
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(panel_1, GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(panel, GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
					.addGap(51)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_4, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
									.addComponent(homeButton, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
									.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
									.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
									.addGap(60))))
						.addGroup(layout.createSequentialGroup()
							.addComponent(label_3, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
							.addGap(230))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(44, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addGap(14)
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
							.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
							.addGap(31)
							.addComponent(label_3, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
							.addGap(38)
							.addComponent(label_4, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
							.addGap(55))
						.addGroup(layout.createSequentialGroup()
							.addComponent(homeButton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
							.addGap(24))))
		);
		
		label_1 = new JLabel();
		label_1.setForeground(new Color(153, 51, 153));
		label_1.setFont(new Font("Trattatello", Font.BOLD, 14));
		label_1.setBounds(104, 18, 112, 17);
		panel_1.add(label_1);
		
		label_6 = new JLabel("");
		label_6.setBounds(27, 48, 210, 36);
		panel_1.add(label_6);
		panel.setLayout(null);
		
		label = new JLabel();
		label.setForeground(new Color(0, 51, 204));
		label.setFont(new Font("Trattatello", Font.BOLD, 14));
		label.setBounds(98, 18, 115, 17);
		panel.add(label);
		
		label_5 = new JLabel("");
		label_5.setBounds(30, 47, 210, 36);
		panel.add(label_5);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:

		MainMenu c = new MainMenu(this.role, this.customer_id, this.customer_name);
		c.permissions(this.role);
		this.hide();
		c.setVisible(true);

	}
	public void getData() {
		int CC;

		try {
			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();

			insert = con1.prepareStatement("select * from offers");
			ResultSet Rs = insert.executeQuery();
			ResultSetMetaData RSMD = Rs.getMetaData();
//			CC = RSMD.getColumnCount();
			
			Rs.next();
			jLabel1.setText(Rs.getString("offer_name"));
			lblNewLabel.setText(Rs.getString("offer_details"));
			
			Rs.next();
			label.setText(Rs.getString("offer_name"));
			label_5.setText(Rs.getString("offer_details"));
			
			
			Rs.next();
			label_1.setText(Rs.getString("offer_name"));
			label_6.setText(Rs.getString("offer_details"));
			
			
			
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		setVisible(false); // you can't see me!
		dispose();

	}// GEN-LAST:event_jButton3ActionPerformed

	public void permissions(String role) {
		this.role = role;

		if (role.contentEquals("admin")) {
//			add what ever you want to admin permissions 
			homeButton.setVisible(false);
		} else {
			homeButton.setVisible(true);

		}

	}
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private JButton homeButton;
	private String role = "user";
	private String customer_id;
	private String customer_name;
	private JPanel panel;
	private JPanel panel_1;
	private JLabel label;
	private JLabel label_1;
	private JLabel label_2;
	private JLabel label_3;
	private JLabel label_4;
	private JLabel lblNewLabel;
	private JLabel label_5;
	private JLabel label_6;
	// End of variables declaration//GEN-END:variables
}
