/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author kobinath
 */
public class Profile extends JFrame {

	/**
	 * Creates new form customer
	 */
	public Profile(String role, String customer_id, String customer_name) {
		this.role = role;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		initComponents();
		autoId();

	}

	Connection con1;
	PreparedStatement insert;
	ResultSet rs1;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		txtstreet = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtcity = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		txtmobile = new javax.swing.JTextField();
		txtfname = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txtlname = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

		jLabel3.setText("Address");

		jLabel4.setText("City");

		jLabel6.setText("Mobile");

		jLabel1.setText("First Name");

		jLabel2.setText("Last Name");

		jLabel7.setText("Customer No");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(0, 102, 255));
		jLabel8.setText("jLabel8");

		jButton1.setText("Update");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		lblEmail = new JLabel();
		lblEmail.setText("Email");

		textMail = new JTextField();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(41)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel1)
						.addComponent(jLabel5)
						.addComponent(jLabel7)
						.addComponent(lblEmail)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
							.addComponent(jLabel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jLabel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
					.addGap(19)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(textMail, GroupLayout.PREFERRED_SIZE, 262, GroupLayout.PREFERRED_SIZE)
							.addGap(168))
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(txtmobile, 262, 262, 262)
								.addContainerGap())
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addComponent(jLabel8)
									.addContainerGap(423, Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
											.addGroup(jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
													.addComponent(txtlname, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
													.addComponent(txtfname, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 262, GroupLayout.PREFERRED_SIZE))
												.addGap(46))
											.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(txtstreet, 262, 262, 262)
												.addPreferredGap(ComponentPlacement.RELATED)))
										.addGroup(jPanel1Layout.createSequentialGroup()
											.addComponent(txtcity, 262, 262, 262)
											.addPreferredGap(ComponentPlacement.RELATED)))
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 85, Short.MAX_VALUE))
									.addGap(37))))))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel8)
						.addComponent(jLabel7))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(txtfname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel1))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(txtlname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txtstreet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txtcity, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
							.addGap(13)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
									.addComponent(jLabel6)
									.addComponent(txtmobile, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(26)
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
							.addGap(4)
							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblEmail)
						.addComponent(textMail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(106, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		jLabel9.setText("Customer ");

		homeButton = new JButton("Home");
		homeButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				homeButtonActionPerformed(e);
			}
		});
		homeButton.setBackground(new Color(51, 153, 102));
		homeButton.setForeground(new Color(0, 0, 0));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(29)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 578, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel9)
							.addPreferredGap(ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
							.addComponent(homeButton)
							.addGap(33))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(11)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel9)
						.addComponent(homeButton, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
					.addGap(65))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:

		MainMenu c = new MainMenu(this.role, this.customer_id, this.customer_name);
		c.permissions(this.role);
		this.hide();
		c.setVisible(true);

	}

	public void autoId() {
		try {
			jLabel8.setText(this.customer_id);
			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();
			insert = con1.prepareStatement("SELECT firstname, lastname, street, city, phone, mail FROM customer where cust_id=?");
			insert.setString(1, this.customer_id);
			rs1 = insert.executeQuery();

			if (rs1.next() == false) {
			} else {
				String firstname = rs1.getString(1);
				String lastname = rs1.getString(2);
				String street = rs1.getString(3);
				String city = rs1.getString(4);
				String phone = rs1.getString(5);
				String mail = rs1.getString(6);	
				
				txtfname.setText(firstname);
				txtlname.setText(lastname);
				txtstreet.setText(street);
				txtcity.setText(city);
				txtmobile.setText(phone);
				textMail.setText(mail);

			}
			
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:

		try {
			String id = jLabel8.getText();
			String fname = txtfname.getText();
			String lname = txtlname.getText();
			String street = txtstreet.getText();
			String city = txtcity.getText();
			String mobile = txtmobile.getText();
			String mail = textMail.getText();

			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();
			insert = con1.prepareStatement(
					"UPDATE customer SET firstname=?, lastname=?, street=?, city=?, phone=?, mail=? WHERE  cust_id=?");
//			
			insert.setString(1, fname);
			insert.setString(2, lname);
			insert.setString(3, street);
			insert.setString(4, city);
			insert.setString(5, mobile);
			insert.setString(6, mail);
			insert.setString(7, id);
			insert.executeUpdate();

//			insert = con1.prepareStatement("insert into logins(username, password, whois, role) values (?,?,?,?)");
//
//			insert.setString(3, id);
//			insert.setString(4, "user");
//			insert.executeUpdate();

			JOptionPane.showMessageDialog(this, "Sucsessfully Saved");
//			autoId();
//			txtfname.setText("");
//			txtlname.setText("");
//			txtstreet.setText("");
//			txtcity.setText("");
//			txtmobile.setText("");
//			textMail.setText("");

			// table_update();

		} catch (SQLException ex) {
			Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		setVisible(false); // you can't see me!
		dispose();

	}// GEN-LAST:event_jButton2ActionPerformed

	public void permissions(String role) {
		// TODO Auto-generated method stub
		this.role = role;
		if (this.role == "admin") {
			homeButton.setVisible(false);
		} else {
			homeButton.setVisible(true);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton homeButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField txtcity;
	private javax.swing.JTextField txtfname;
	private javax.swing.JTextField txtlname;
	private javax.swing.JTextField txtmobile;
	private javax.swing.JTextField txtstreet;
	private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
	private JLabel lblEmail;
	private JTextField textMail;
	private String role = "user";
	private String customer_id;
	private String customer_name;
}
