
package bank;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JPanel;

/**
 *
 * @author Zen jah Class Login that gives access to users after verifying
 *         username and password.
 */
public class VirtualCard extends JFrame {

	/**
	 * Creates new form 'login'
	 * 
	 */
	public VirtualCard() {
		initComponents();
	}
	
	public VirtualCard(String role, String customer_id, String customer_name) {
		this.role = role;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		initComponents();
		data();
	}
	

	public void data() {
		try {
			DB_Connector connector = new DB_Connector();
			con1 = connector.getConnection();
			insert = con1.prepareStatement("select * from virtual_cards where cust_id=?");
			insert.setString(1, this.customer_id);

			ResultSet Rs = insert.executeQuery();
			ResultSetMetaData RSMD = Rs.getMetaData();
//			CC = RSMD.getColumnCount();
			
			Rs.next();

			String val1 = ""+((int)(Math.random()*9000)+1000);
			String val2 = ""+((int)(Math.random()*9000)+1000);
			String val3 = ""+((int)(Math.random()*9000)+1000);
			String val4 = ""+((int)(Math.random()*9000)+1000);
			String Iban = val1 + ' ' + val2 + ' '+ val3 + ' '+ val4 + ' ';
			String cvv = Double.toString((Math.random() * 800) + 100);
			
			label_2.setText(this.customer_name);
			label_3.setText(Rs.getString("iban"));
			label_4.setText(Rs.getString("data"));
			label_5.setText(Rs.getString("cvv"));
//			jLabel1.setText(Rs.getString("offer_name"));
//			lblNewLabel.setText(Rs.getString("offer_details"));
//			
//			Rs.next();
//			label.setText(Rs.getString("offer_name"));
//			label_5.setText(Rs.getString("offer_details"));
//			
//			
//			Rs.next();
//			label_1.setText(Rs.getString("offer_name"));
//			label_6.setText(Rs.getString("offer_details"));
//			
			
			
		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}

	
	/**
	 * This method is called from within the constructor to initialize the form. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	private void initComponents() {
		setSize(900, 600);
		jPanel1 = new javax.swing.JPanel();
		
		setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
		setTitle("Login");
		setBackground(new java.awt.Color(0, 102, 255));
		setForeground(new java.awt.Color(0, 102, 255));

//		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("asd"));
		// here!!!
		jPanel1.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
		
		JLabel lblYourVirtualCard = new JLabel("Your Virtual Card");
		lblYourVirtualCard.setForeground(Color.BLUE);
		lblYourVirtualCard.setFont(new Font("Trattatello", Font.BOLD, 32));
		
		label_2 = new JLabel((String) null);
		label_2.setFont(new Font("Lucida Grande", Font.BOLD, 13));
		
		label_3 = new JLabel((String) null);
		label_3.setFont(new Font("Lucida Grande", Font.BOLD, 13));
		
		label_4 = new JLabel((String) null);
		label_4.setFont(new Font("Lucida Grande", Font.BOLD, 13));
		
		label_5 = new JLabel((String) null);
		label_5.setFont(new Font("Lucida Grande", Font.BOLD, 13));
		
		JLabel label_6 = new JLabel("Name");
		
		JLabel label_7 = new JLabel("Iban");
		
		JLabel label_8 = new JLabel("Expire");
		
		JLabel label_9 = new JLabel("CVV");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(82)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(label_7)
						.addComponent(label_9)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
							.addComponent(label_3, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(label_8)
								.addGap(30)
								.addComponent(label_4, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
							.addComponent(label_5, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(label_6)
								.addGap(30)
								.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(29)
							.addComponent(lblYourVirtualCard)))
					.addContainerGap(109, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(19)
					.addComponent(lblYourVirtualCard, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
					.addGap(12)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(label_6)
						.addComponent(label_2))
					.addGap(12)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(label_7)
						.addComponent(label_3))
					.addGap(12)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(label_8)
						.addComponent(label_4))
					.addGap(9)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(label_9)
						.addComponent(label_5))
					.addContainerGap(23, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);
		 
		JLabel label = new JLabel(new ImageIcon("C:\\Users\\KNIGHT\\Desktop\\pic\\card9.jpg"));
		label.setBackground(Color.BLUE);
		setContentPane(label);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(20)
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(2500, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGap(69)
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(1337, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
//		   setLayout(new BorderLayout());
//		   setLayeredPane((new ImageIcon(this.getClass().getResource("/z.jpg")).getImage())); 
	}

	/**
	 * set required parameters for login (used for unit tests)
	 * 
	 * @param data1 Username
	 * @param data2 Password
	 * 
	 */
	

	/**
	 * Verify if username and password do not match.
	 * 
	 * @param test test flag for unit test
	 * @return status of login
	 */

	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}
	public void permissions(String role) {
		this.role = role;

		if (role.contentEquals("admin")) {
//			add what ever you want to admin permissions 
//			homeButton.setVisible(false);
		} else {
//			homeButton.setVisible(true);

		}

	}
	private javax.swing.JPanel jPanel1;
	private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
	private String role;
	private String customer_id;
	private String customer_name;
	private JLabel label_2;
	private JLabel label_3;
	private JLabel label_4;
	private JLabel label_5;
	Connection con1;
	PreparedStatement insert;
	ResultSet rs1;
}
